### ISSUE TITLE
is it working with bs4?

### ISSUE THREAD

**Issue by mbunal** [jhaygt/bootstrap-multimodal#4]
i cant run with bs4! topmodal opened and closed. but there is still backdrop after closed topmodal. and mymodal is not accessieble.

**Comment by huumn** [comment]
You need to change the 'show.bs.modal' to 'shown.bs.modal' and it works fine on bs4.

**Comment by mbunal** [comment]
i changed it is working but backdrop is working not properly now. first modal is ok. but there are backdrops after first modal.

**Comment by huumn** [comment]
You're right. I ended up changing this function to get it right (without changing to 'shown').

```js
MultiModal.prototype.show = function (target) {
        var that = this;
        var $target = $(target);

        that.modalCount = getModalCount() + 1;

        that.adjustModal($target);
        that.adjustBackdrop();

        // we only want one backdrop; hide any extras
        $('.modal-backdrop').not(':first').addClass('hidden');
};
```

**Comment by mbunal** [comment]
yes, this works more flawless. but there are backdrops for each modal. when u open every modal, background is getting darker.

**Comment by mbunal** [comment]
hidden class removed in bs4. i used d.none but i think there is a problem in counting.

**Comment by mbunal** [comment]
https://jsfiddle.net/mbunal/ay0gkjzc/2/

**Comment by mbunal** [comment]
finally solved. i changes to:

```
MultiModal.prototype.show = function (target) {
    var that = this;
    var $target = $(target);

    // Bootstrap triggers the show event at the beginning of the show function and before
    // the modal backdrop element has been created. The timeout here allows the modal
    // show function to complete, after which the modal backdrop will have been created
    // and appended to the DOM.
    window.setTimeout(function () {
        that.modalCount = getModalCount() + 1;

        // we only want one backdrop; hide any extras
        if (that.modalCount > 1)
            $('.modal-backdrop').not(':first').addClass('d-none');

        that.adjustModal($target);
        that.adjustBackdrop();
    });
};
```
its working now with bs4:
[https://jsfiddle.net/4mwt2syc/1/](https://jsfiddle.net/4mwt2syc/1/)
